# Labels configuration for the repository
# Run: gh label sync -f .github/labels.yml

# Type labels
- name: "type/feature"
  color: "0e8a16"
  description: "New feature or request"

- name: "type/bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type/documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "type/style"
  color: "fbca04"
  description: "Code style improvements"

- name: "type/refactor"
  color: "fbca04"
  description: "Code refactoring"

- name: "type/performance"
  color: "0e8a16"
  description: "Performance improvements"

- name: "type/test"
  color: "0e8a16"
  description: "Adding or updating tests"

- name: "type/chore"
  color: "fef2c0"
  description: "Maintenance tasks"

- name: "type/ci"
  color: "0052cc"
  description: "CI/CD related changes"

- name: "type/build"
  color: "0052cc"
  description: "Build system changes"

# Size labels
- name: "size/xs"
  color: "00ff00"
  description: "Extra small PR (< 10 lines)"

- name: "size/s"
  color: "77ff00"
  description: "Small PR (10-100 lines)"

- name: "size/m"
  color: "ffff00"
  description: "Medium PR (100-500 lines)"

- name: "size/l"
  color: "ff7700"
  description: "Large PR (500-1000 lines)"

- name: "size/xl"
  color: "ff0000"
  description: "Extra large PR (> 1000 lines)"

# Area labels
- name: "area/gui"
  color: "c5def5"
  description: "GUI related changes"

- name: "area/core"
  color: "c5def5"
  description: "Core functionality changes"

- name: "area/build"
  color: "c5def5"
  description: "Build system changes"

- name: "area/ci"
  color: "c5def5"
  description: "CI/CD changes"

- name: "area/docs"
  color: "c5def5"
  description: "Documentation changes"

- name: "area/tests"
  color: "c5def5"
  description: "Test related changes"

# Priority labels
- name: "priority/critical"
  color: "b60205"
  description: "Critical priority"

- name: "priority/high"
  color: "d93f0b"
  description: "High priority"

- name: "priority/medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority/low"
  color: "0e8a16"
  description: "Low priority"

# Status labels
- name: "status/needs-triage"
  color: "ededed"
  description: "Needs triage"

- name: "status/in-progress"
  color: "0052cc"
  description: "Work in progress"

- name: "status/blocked"
  color: "b60205"
  description: "Blocked by something"

- name: "status/ready-for-review"
  color: "0e8a16"
  description: "Ready for review"

- name: "status/changes-requested"
  color: "fbca04"
  description: "Changes requested"

# Special labels
- name: "breaking-change"
  color: "b60205"
  description: "Breaking change"

- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"

- name: "security"
  color: "b60205"
  description: "Security related"

- name: "good-first-issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help-wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "needs-description"
  color: "ededed"
  description: "Needs a better description"

- name: "no-issue-linked"
  color: "ededed"
  description: "No issue linked"

- name: "invalid-branch-name"
  color: "e99695"
  description: "Branch name doesn't follow convention"

- name: "merge-conflict"
  color: "b60205"
  description: "Has merge conflicts"

- name: "stale"
  color: "ededed"
  description: "Stale issue or PR"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or PR already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"