version: v1
labels:
  # Feature: New feature or enhancement (e.g., "feat: add user authentication")
  - label: 'feat'
    matcher:
      title: '^feat(\(.*\))?: .*'
      
  # Bug Fix: Corrects an error (e.g., "fix: broken link on homepage")
  - label: 'fix'
    matcher:
      title: '^fix(\(.*\))?: .*'
      
  # Breaking Change: Identifies a change that breaks compatibility (if "BREAKING CHANGE" is in the title or body)
  - label: 'breaking change'
    matcher:
      title: 'BREAKING CHANGE'
      body: 'BREAKING CHANGE'
      
  # Chore: Maintenance tasks (e.g., "chore: update dependencies")
  - label: 'chore'
    matcher:
      title: '^chore(\(.*\))?: .*'
      
  # Docs: Documentation changes
  - label: 'docs'
    matcher:
      title: '^docs(\(.*\))?: .*'
      
  # Refactor: Code change that neither fixes a bug nor adds a feature
  - label: 'refactor'
    matcher:
      title: '^refactor(\(.*\))?: .*'