blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/JoShMiQueL/cookie-clicker-bot/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/JoShMiQueL/cookie-clicker-bot#readme
    about: Read the documentation
  - name: 🔒 Security Issue
    url: https://github.com/JoShMiQueL/cookie-clicker-bot/security/advisories/new
    about: Report a security vulnerability privately
