name: Build Executable

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Build executable
        run: |
          pyinstaller CookieClickerBot.spec

      - name: Get executable size
        id: size
        shell: pwsh
        run: |
          $size = (Get-Item "dist\CookieClickerBot.exe").Length
          $sizeMB = [math]::Round($size / 1MB, 2)
          echo "size_bytes=$size" >> $env:GITHUB_OUTPUT
          echo "size_mb=$sizeMB" >> $env:GITHUB_OUTPUT
          echo "Executable size: $sizeMB MB"

      - name: Calculate checksum
        id: checksum
        shell: pwsh
        run: |
          $hash = (Get-FileHash "dist\CookieClickerBot.exe" -Algorithm SHA256).Hash
          echo "sha256=$hash" >> $env:GITHUB_OUTPUT
          echo "SHA256: $hash"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CookieClickerBot-${{ github.sha }}
          path: dist/CookieClickerBot.exe
          retention-days: 30

      - name: Create build info
        shell: pwsh
        run: |
          @"
          Build Information
          ==================
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref_name }}
          Size: ${{ steps.size.outputs.size_mb }} MB
          SHA256: ${{ steps.checksum.outputs.sha256 }}
          "@ | Out-File -FilePath dist/BUILD_INFO.txt

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info-${{ github.sha }}
          path: dist/BUILD_INFO.txt
          retention-days: 30

      - name: Comment PR with build info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const size = '${{ steps.size.outputs.size_mb }}';
            const sha = '${{ steps.checksum.outputs.sha256 }}';
            const body = `## 🔨 Build Successful

            **Executable Size:** ${size} MB
            **SHA256:** \`${sha.substring(0, 16)}...\`

            Download the artifact from the workflow run to test.`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
