name: Quality Checks

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        type: string
        default: '3.12'
    outputs:
      passed:
        description: 'Whether quality checks passed'
        value: ${{ jobs.quality-checks.outputs.passed }}

jobs:
  quality-checks:
    name: Code Quality Validation
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.final.outputs.passed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run linting and formatting
        run: |
          # Run pre-commit hooks (includes black, flake8, etc.)
          pre-commit run --all-files

      - name: Run static type checking
        run: |
          # Run mypy if configured
          if [ -f "mypy.ini" ] || [ -f ".mypy.ini" ] || grep -q "mypy" pyproject.toml; then
            mypy src/ || echo "MyPy found issues but continuing..."
          else
            echo "MyPy not configured, skipping type checking"
          fi

      - name: Check for security vulnerabilities
        run: |
          # Run safety check
          safety check || echo "Security issues found but continuing..."

      - name: Validate configuration files
        run: |
          # Check if pyproject.toml is valid
          python -c "import tomllib; tomllib.load(open('pyproject.toml', 'rb'))"
          echo "✅ pyproject.toml is valid"

      - name: Final quality check status
        id: final
        run: |
          echo "passed=true" >> $GITHUB_OUTPUT
          echo "✅ All quality checks completed"
