name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Build executable
        run: |
          pyinstaller CookieClickerBot.spec --clean

      - name: Calculate checksum
        run: |
          certutil -hashfile dist/CookieClickerBot.exe SHA256 > dist/CookieClickerBot.exe.sha256

      - name: Generate changelog
        id: changelog
        run: |
          $previousTag = git describe --tags --abbrev=0 HEAD^ 2>$null
          if ($previousTag) {
            $changelog = git log "$previousTag..HEAD" --pretty=format:"- %s (%h)" --no-merges
          } else {
            $changelog = git log --pretty=format:"- %s (%h)" --no-merges
          }
          $changelog = $changelog -join "`n"
          echo "CHANGELOG<<EOF" >> $env:GITHUB_OUTPUT
          echo $changelog >> $env:GITHUB_OUTPUT
          echo "EOF" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/CookieClickerBot.exe
            dist/CookieClickerBot.exe.sha256
          body: |
            ## 🎮 Cookie Clicker Autoclicker ${{ github.ref_name }}

            ### 📦 Downloads
            - **Windows Executable**: CookieClickerBot.exe
            - **SHA256 Checksum**: CookieClickerBot.exe.sha256

            ### ✨ What's New
            ${{ steps.changelog.outputs.CHANGELOG }}

            ### 📝 Installation
            1. Download `CookieClickerBot.exe`
            2. Run the executable (no installation required)
            3. Open Cookie Clicker in Steam
            4. Click "Start" in the GUI

            ### 🔒 Security
            Verify the download integrity using the SHA256 checksum:
            ```bash
            certutil -hashfile CookieClickerBot.exe SHA256
            ```

            ### 📚 Documentation
            See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for full documentation.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
