name: Semantic Pull Request Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR Title against Conventional Commits
        uses: amannn/action-semantic-pull-request@v5 
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}